color = ''
project-name = 'default'
[default]
account_id = 'acct_1Pv0WgJsy3hrb9cx'
device_name = 'DESKTOP-FURIB02'
display_name = 'kaash'
live_mode_api_key = 'rk_live_***********************************************************************************************S4xa'
live_mode_key_expires_at = '2024-12-12'
live_mode_pub_key = 'pk_live_51Pv0WgJsy3hrb9cxiT9AMV168XM3900BlN3vK1yO0xnAUreR71aadyBEfRGBQJDBjyqh5FKElp7SUEd1sYKrYmZO00ezGyGISq'
test_mode_api_key = 'rk_test_51Pv0WgJsy3hrb9cxDcb1IhiCr6aCa8hLSemCIkuMPNLvyxVQQEuhYQtEErHLV4nwJ3RBfaqU770ahJ6nJgRXSUnD00sw5KqHJ2'
test_mode_key_expires_at = '2024-12-12'
test_mode_pub_key = 'pk_test_51Pv0WgJsy3hrb9cxGDdKG3yxPKs4v628vouA4kEsAUAeeOm6koNDm67R3eOjt6ut83onbB11qOjTZpLXmTmeIJw400xlCcGgkY'

